site_name: NeuralProphet
nav:
  - 'NeuralProphet':
      - 'Quickstart': 'README.md'
      - 'Model Overview': 'model-overview.md'
  - 'Model Components':
    - 'Trend': 'model/trend.md'
    - 'Seasonality': 'model/seasonality.md'
    - 'Auto-Regression': 'model/auto-regression.md'
    - 'Lagged Regressors': 'model/lagged-regressors.md'
    - 'Events': 'model/events.md'
    - 'Future Regressors': 'model/future-regressors.md'
  - 'About':
    - 'Contribute': 'contribute.md'
theme: readthedocs
markdown_extensions:
    - attr_list